# Generated by Django 2.2.6 on 2019-12-01 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_userinfo_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='gender',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='test',
            field=models.EmailField(max_length=19, null=True),
        ),
    ]
